# Generated by Django 4.2.4 on 2023-09-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donateur", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockSang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupesanguin", models.CharField(max_length=10)),
                ("unite", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DemandedeSang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomPatient", models.CharField(max_length=30)),
                ("agePatient", models.PositiveIntegerField()),
                ("raison", models.CharField(max_length=500)),
                ("groupesanguin", models.CharField(max_length=10)),
                ("unite", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="En-Attente", max_length=20)),
                ("date", models.DateField(auto_now=True)),
                (
                    "demande_du_donateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donateur.donateur",
                    ),
                ),
                (
                    "demande_du_patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
